name: cleverbot
description: A wrapper for interacting with the Cleverbot API. Get your API key at http://www.cleverbot.com/api
version: 0.2.1
author: rinukkusu <rinukkusu@auen.land>
homepage: https://github.com/rinukkusu/cleverbot-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0