name: cleverbot
description: A wrapper for interacting with the Cleverbot API.
version: 0.2.0
author: rinukkusu <rinukkusu@auen.land>
homepage: https://github.com/rinukkusu/cleverbot-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0